import Icon from "@/src/components/ui/Icon";
import DemoCampaignLabel from "./DemoCampaignLabel";
import { RewardBadge } from "@/src/components/ui/Brand";
import Link from "next/link";
import {isLocalRewardAdmin} from "@/src/lib/rewards/adminAccess";
import {getSponsorCatalog} from "@/src/lib/campaigns/sponsorQueries";
import {participantCampaignGroups} from "@/src/lib/campaigns/participantVisibility";
import {getRewardOverview} from "@/src/lib/redemptions/queries";
import {getCampaignRewardTotals} from "@/src/lib/rewards/getCampaignRewardTotals";

export default async function MyCampaigns(){
 const localAdmin=await isLocalRewardAdmin();
 const catalog=await getSponsorCatalog().catch(()=>null);const overview=await getRewardOverview().catch(()=>null);
 if(!catalog)return <p id="my-campaigns" className="mt-5 text-sm text-amber-800">My campaigns unavailable. Check campaign setup.</p>;
 const {joined}=participantCampaignGroups(catalog);
 const balances=await Promise.all(joined.map(c=>getCampaignRewardTotals(c.id).catch(()=>null)));
 return <section id="my-campaigns" className="mt-7 min-w-0 scroll-mt-6 space-y-3"><div className="flex items-center justify-between gap-4"><div><h2 className="section-title">My campaigns</h2>{!localAdmin&&<p className="mt-1 text-xs text-slate-500">Public preview · participant view</p>}</div><Link href="/rewards" className="shrink-0 text-xs text-teal-700">My rewards →</Link></div>{!joined.length?<div className="panel p-5"><p className="text-sm text-slate-500">You haven’t joined a campaign yet. Find a campaign that fits your next move.</p><Link href="/challenges" className="mt-3 inline-block text-sm font-medium text-teal-700">Explore available campaigns →</Link></div>:<div className="-mx-5 overflow-x-auto px-5 pb-2 [scrollbar-width:thin] sm:-mx-8 sm:px-8 lg:-mx-12 lg:px-12"><div className="flex w-max snap-x snap-mandatory gap-4">{joined.map((c,index)=>{const progress=overview?.campaigns.find(b=>b.campaign_id===c.id);const membership=catalog.participants.find(p=>p.campaign_id===c.id&&p.user_id===catalog.userId);const balance=balances[index];return <article key={c.id} className="panel campaign-card w-[calc(100vw-3.25rem)] max-w-[26rem] shrink-0 snap-start p-5 sm:w-[calc(50vw-2.5rem)] lg:w-[calc((100vw-9rem)/3)] xl:w-[26rem]"><div className="mb-3 flex items-center gap-3"><span className="campaign-icon"><Icon name="campaign"/></span><h3 className="font-semibold">{c.name}<DemoCampaignLabel/></h3></div><p className="mt-1 text-xs text-slate-500">{catalog.organisations.find(o=>o.id===c.organisation_id)?.name}</p><p className="mt-2 text-xs">Joined · Participation: {membership?.status} · Campaign: {c.status}</p>{progress?<><p className="mt-3 text-sm">Progress: {progress.activity_count} recorded activities · {progress.rewarded_activities} rewarded</p><p className="mt-1 text-xs text-slate-500">{(progress.distance_meters/1000).toFixed(2)} km · {Math.floor(progress.active_minutes)} active minutes</p><p className="mt-3 text-xs text-slate-600"><RewardBadge>{progress.earned.toLocaleString("en-US")} BKNE earned</RewardBadge></p></>:<p className="mt-3 text-xs text-amber-800">Progress and earned balance unavailable. Check redemption migration setup.</p>}<p className="mt-3 text-xs text-slate-500">Remaining reward pool: {(balance?.remainingPool??c.remaining_pool).toLocaleString("en-US")} BKNE</p><Link href="/challenges" className="mt-4 inline-block text-sm font-medium text-teal-700">View campaign →</Link></article>})}</div></div>}</section>;
}