"use server";
import { revalidatePath } from "next/cache";
import { isLocalRewardAdmin } from "@/src/lib/rewards/adminAccess";
import { getRewardTransactionStatus, prepareRewardTransfer, reconcileExistingRewardTransfer, releaseStuckRewardSubmission, submitSignedRewardTransfer } from "@/src/lib/brickken/distributeReward";
import { getRewardSigningPackage } from "./signingPackage";
const clean=(f:FormData)=>[...f.keys()].filter(k=>!k.startsWith("$ACTION_")).sort().join(","); const refresh=()=>{revalidatePath("/admin/rewards");revalidatePath("/");};
export async function prepareBrickkenDistribution(_: {message:string;preparation?:unknown},f:FormData){if(!await isLocalRewardAdmin())return {message:"Local admin only."};const id=f.get("rewardId");if(clean(f)!=="rewardId"||typeof id!=="string")return {message:"Invalid reward ID."};try{const preparation=await prepareRewardTransfer(id);refresh();return {message:"Prepared. Sign outside this app.",preparation};}catch(e){return {message:e instanceof Error?e.message:"Unable to prepare."};}}
export async function submitBrickkenDistribution(_: {message:string},f:FormData){if(!await isLocalRewardAdmin())return {message:"Local admin only."};const id=f.get("rewardId"),tx=f.get("txId"),signed=f.get("signedTransaction");if(clean(f)!=="rewardId,signedTransaction,txId"||typeof id!=="string"||typeof tx!=="string"||typeof signed!=="string")return {message:"Signed transaction details are incomplete."};try{await submitSignedRewardTransfer(id,tx,signed);refresh();return {message:"Submitted; poll status and do not resubmit."};}catch(e){return {message:e instanceof Error?e.message:"Unable to submit."};}}
export async function pollBrickkenDistribution(_: {message:string},f:FormData){if(!await isLocalRewardAdmin())return {message:"Local admin only."};const id=f.get("rewardId");if(clean(f)!=="rewardId"||typeof id!=="string")return {message:"Invalid reward ID."};try{const result=await getRewardTransactionStatus(id);refresh();return {message:result.status==="distributed"?"Confirmed and distributed.":result.status==="failed"?"Rejected; safe retry is available.":"Still confirming. Do not resubmit."};}catch(e){return {message:e instanceof Error?e.message:"Unable to poll."};}}
export async function reconcileBrickkenDistribution(_: {message:string},f:FormData){if(!await isLocalRewardAdmin())return {message:"Local admin only."};const id=f.get("rewardId"),tx=f.get("txId"),hash=f.get("transactionHash"),confirm=f.get("confirmation");if(clean(f)!=="confirmation,rewardId,transactionHash,txId"||typeof id!=="string"||typeof tx!=="string"||typeof hash!=="string"||typeof confirm!=="string")return {message:"Historical reconciliation evidence is incomplete."};try{await reconcileExistingRewardTransfer(id,tx,hash,confirm);refresh();return {message:"Manual historical reconciliation recorded."};}catch(e){return {message:e instanceof Error?e.message:"Unable to reconcile."};}}
export async function releaseBrickkenSubmissionClaim(_: {message:string},f:FormData){if(!await isLocalRewardAdmin())return {message:"Local admin only."};const id=f.get("rewardId"),tx=f.get("txId"),confirm=f.get("confirmation");if(clean(f)!=="confirmation,rewardId,txId"||typeof id!=="string"||typeof tx!=="string"||confirm!=="RELEASE")return {message:"Explicit recovery confirmation is required."};try{const result=await releaseStuckRewardSubmission(id,tx);refresh();return {message:result.message};}catch(e){return {message:e instanceof Error?e.message:"Unable to release claim."};}}

export async function getRewardSigningPackageAction(rewardId:string){return getRewardSigningPackage(rewardId);}
