"use client";
import {useActionState,useState} from "react";
import {requestRedemption} from "@/src/lib/redemptions/actions";
import {redemptionOptions,type RedemptionType} from "@/src/lib/redemptions/types";
export default function RedemptionForm({campaigns,requestId}:{campaigns:{id:string;name:string;available:number;rate:number|null}[];requestId:string}){
 const [state,action,pending]=useActionState(requestRedemption,{message:""});
 const [stableId]=useState(requestId);const [campaignId,setCampaignId]=useState(campaigns[0]?.id??"");const [type,setType]=useState<RedemptionType>("cash");const [amount,setAmount]=useState("");
 const campaign=campaigns.find(c=>c.id===campaignId);const preview=campaign?.rate?Number(amount)/campaign.rate:null;
 const cls="mt-1 block w-full rounded border border-slate-300 bg-white p-2";
 if(state.redemption)return <section className="panel space-y-3 p-5"><h2 className="font-semibold">Request saved</h2><p role="status">{state.message}</p><p>{state.redemption.amount_bkne} BKNE{state.redemption.euro_value!==null&&<> · €{Number(state.redemption.euro_value).toFixed(2)} reward value</>}</p><p>Status: {state.redemption.status}</p><a href="/rewards" className="inline-block text-sm text-teal-700">Refresh balance / start another request →</a></section>;
 return <form action={action} className="panel space-y-4 p-5"><h2 className="text-lg font-semibold">Use your rewards</h2><p className="text-xs text-slate-500">Only distributed BKNE is available. Select one campaign so its funded reward value applies.</p><input type="hidden" name="requestId" value={stableId}/><label className="block text-sm">Campaign<select required name="campaignId" value={campaignId} onChange={e=>setCampaignId(e.target.value)} className={cls}><option value="">Select campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.available} BKNE available</option>)}</select></label><label className="block text-sm">Redemption option<select name="type" value={type} onChange={e=>setType(e.target.value as RedemptionType)} className={cls}>{Object.entries(redemptionOptions).map(([value,o])=><option key={value} value={value}>{o.label}</option>)}</select></label><label className="block text-sm">{type==="donation"?"Charity (demo)":"Destination (demo)"}<select key={type} name="destination" className={cls}>{redemptionOptions[type].destinations.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><label className="block text-sm">Amount BKNE<input required name="amount" type="number" min="1" step="1" max={campaign?.available??0} value={amount} onChange={e=>setAmount(e.target.value)} className={cls}/></label>{type==="hold"?<p className="text-sm">Keeping BKNE records your preference. It does not spend or lock your balance.</p>:campaign?.rate?<div className="rounded bg-teal-50 p-4 text-teal-900"><p>{Number(amount||0).toLocaleString("en-US")} BKNE = <strong>€{Number.isFinite(preview)?preview?.toFixed(2):"0.00"}</strong> reward value</p><p className="mt-1 text-xs">{campaign.rate} BKNE = €1 · Campaign-funded conversion, not an exchange rate. The server confirms the final value.</p></div>:<p className="text-sm text-amber-800">This campaign has no redemption value configured. You can keep BKNE.</p>}<p className="text-xs text-slate-500">Demo only: no payout, charity payment, webshop order or voucher delivery. Requested, processing, completed and failed redemptions remain committed; refunds are not automated.</p><button disabled={pending||!campaign||campaign.available<=0||(type!=="hold"&&!campaign.rate)} className="rounded bg-teal-700 px-4 py-2 text-sm text-white disabled:opacity-50">{pending?"Saving…":type==="hold"?"Keep BKNE":"Request redemption"}</button><p role="status" className="text-sm text-amber-800">{state.message}</p></form>;
}
