import Link from "next/link";
import {randomUUID} from "node:crypto";
import {isLocalRewardAdmin} from "@/src/lib/rewards/adminAccess";
import {getSponsorCatalog} from "@/src/lib/campaigns/sponsorQueries";
import {getRewardOverview} from "@/src/lib/redemptions/queries";
import {redemptionOptions} from "@/src/lib/redemptions/types";
import RedemptionForm from "@/src/components/redemptions/RedemptionForm";
export default async function RewardsPage(){
 if(!await isLocalRewardAdmin())return <main className="p-8">Participant rewards are available in the local development demo.</main>;
 const catalog=await getSponsorCatalog().catch(()=>null);const overview=await getRewardOverview().catch(()=>null);
 if(!catalog||!overview)return <main className="p-8"><Link href="/" className="text-teal-700">← Dashboard</Link><p className="mt-5">Rewards unavailable. Apply the participant redemption migration and check demo identity setup.</p></main>;
 const t=overview.totals;const options=overview.campaigns.filter(c=>c.distributed>0).map(c=>({id:c.campaign_id,name:catalog.campaigns.find(x=>x.id===c.campaign_id)?.name??"Campaign",available:c.available,rate:c.redemption_bkne_per_eur}));
 return <main className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8"><nav className="flex gap-5 text-sm text-teal-700"><Link href="/">Dashboard</Link><Link href="/challenges">My campaigns & challenges</Link></nav><h1 className="text-3xl font-semibold">Johan’s rewards</h1><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Total BKNE earned",t.earned],["Available BKNE",overview.available],["Pending BKNE",t.pending],["Distributed BKNE",t.distributed]].map(([label,value])=><div key={label} className="panel p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{Number(value).toLocaleString("en-US")}</p></div>)}</div><p className="text-xs text-slate-500">Earned means recorded rewards, including those awaiting distribution. Processing: {t.processing} BKNE · Failed distribution: {t.failed} BKNE. Neither is redeemable. Available means distributed BKNE from a campaign minus committed redemption requests.</p><div className="grid items-start gap-5 md:grid-cols-2"><RedemptionForm campaigns={options} requestId={randomUUID()}/><section className="panel space-y-3 p-5"><h2 className="font-semibold">Demo reward choices</h2><ul className="space-y-2 text-sm"><li>Cash reward / EUR</li><li>Donate to a demo charity</li><li>Sports voucher</li><li>Healthy lunch voucher</li><li>Race entry</li><li>Gym contribution</li><li>Keep BKNE</li></ul><p className="text-xs text-slate-500">Illustration only: at a campaign-funded value of 100 BKNE per €1, 2,500 available BKNE represents a €25 reward. Campaigns without a conversion value cannot request cash, donations or vouchers.</p></section></div><section className="space-y-3"><h2 className="text-lg font-semibold">Recent redemption requests</h2><p className="text-xs text-slate-500">Latest 100 requests. “Keep BKNE” preferences do not reduce your balance.</p>{!overview.redemptions.length&&<p className="text-sm">No requests yet.</p>}{overview.redemptions.map(r=><article key={r.id} className="panel p-4"><h3 className="font-semibold">{redemptionOptions[r.redemption_type].label} · {r.amount_bkne} BKNE</h3><p className="mt-2 text-sm">{catalog.campaigns.find(c=>c.id===r.campaign_id)?.name??"Campaign"} · {redemptionOptions[r.redemption_type].destinations.find(d=>d.id===r.destination)?.label??r.destination}</p><p className="mt-1 text-sm">{r.euro_value!==null&&<>€{Number(r.euro_value).toFixed(2)} reward value · </>}Status: {r.status}</p><p className="mt-2 break-all text-xs text-slate-500">{r.created_at} · Request {r.id}</p></article>)}</section></main>;
}
