import {getRewardAdminClient} from "@/src/lib/supabase/rewardAdmin";
import "server-only";
import CreateRewardButton from "./CreateRewardButton";
import { getRewardForActivity } from "@/src/lib/rewards/getRewardForActivity";

export default async function ActivityRewardStatus({ activityId, verified }: { activityId: string; verified: boolean }) {
  let reward;
  try {
    reward = await getRewardForActivity(activityId);
  } catch {
    return <p role="status" className="mt-4 text-xs text-amber-800">Reward status unavailable. Server credentials and rewards database setup are required.</p>;
  }
  if (!reward) return verified ? <CreateRewardButton activityId={activityId} /> : null;
  const campaign=reward.campaign_id ? await getRewardAdminClient().from("campaigns").select("name").eq("id",reward.campaign_id).maybeSingle() : null;
  return <div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-2 text-xs text-slate-600">Reward generated by: {campaign?.data?.name ?? (reward.campaign_id ? "Campaign unavailable" : "Unassigned legacy reward")} · Recorded reward: {reward.amount} BKNE</p><p className="text-xs text-slate-500">Reward status: <span className="font-semibold capitalize text-slate-700">{reward.status}</span></p>{reward.status === "pending" && <p className="mt-2 text-xs leading-relaxed text-teal-700">Ready for distribution. Brickken connection pending.</p>}{reward.status === "processing" && <p className="mt-2 text-xs text-slate-500">Reward distribution is processing.</p>}{reward.status === "failed" && <p className="mt-2 text-xs text-amber-800">Reward distribution failed. Its budget remains reserved; no additional reward will be created.</p>}{reward.status === "distributed" && reward.transaction_hash && <p className="mt-3 break-all text-xs text-slate-500">Transaction hash: <span className="font-mono">{reward.transaction_hash}</span></p>}</div>;
}
