"use client";
import { useState } from "react";
const signer = "0xE95900Ca65EF152a5D9FEe1c61b71bBeD00dFcF6";
type Tx = { from:string; to:string; value:string; nonce:number; chainId:number; data:string; type:number; gasLimit:string; maxPriorityFeePerGas:string; maxFeePerGas:string };
type Ethereum = { request(args:{method:string;params?:unknown[]}):Promise<unknown> };
export default function WhitelistReview({tx,txId,checksum}:{tx:Tx;txId:string;checksum:string}) {
  const [reviewed,setReviewed]=useState(false); const [pending,setPending]=useState(false); const [hash,setHash]=useState(""); const [error,setError]=useState("");
  async function submit(){ if(!reviewed||pending)return; setPending(true);setError("");try { const ethereum=(window as Window & {ethereum?:Ethereum}).ethereum;if(!ethereum)throw new Error("MetaMask was not found.");const accounts=await ethereum.request({method:"eth_requestAccounts"});const chain=await ethereum.request({method:"eth_chainId"});if(chain!=="0x14a34"||!Array.isArray(accounts)||accounts[0]?.toLowerCase()!==signer.toLowerCase())throw new Error("Select Base Sepolia and the dedicated BKNergy wallet.");const result=await ethereum.request({method:"eth_sendTransaction",params:[{chainId:"0x14a34",from:tx.from,to:tx.to,value:tx.value,nonce:"0x2",data:tx.data,type:"0x2",gas:"0x"+BigInt(tx.gasLimit).toString(16),maxPriorityFeePerGas:"0x"+BigInt(tx.maxPriorityFeePerGas).toString(16),maxFeePerGas:"0x"+BigInt(tx.maxFeePerGas).toString(16)}]});if(typeof result!=="string"||!/^0x[0-9a-f]{64}$/i.test(result))throw new Error("MetaMask did not return a transaction hash.");setHash(result);}catch(e){setError(e instanceof Error?e.message:"Wallet request was not completed.");}finally{setPending(false);}}
  const rows=[["Preparation ID",txId],["Chain","Base Sepolia · 84532"],["Prepared nonce",String(tx.nonce)],["From",tx.from],["To",tx.to],["Value",tx.value],["Gas limit",tx.gasLimit],["Calldata","196 bytes"],["Calldata SHA-256",checksum]];
  return <main className="admin-surface mx-auto max-w-4xl space-y-6 p-6 md:p-10"><div><p className="text-sm font-semibold text-amber-700">LOCAL DEVELOPMENT · SANDBOX</p><h1 className="mt-2 text-3xl font-bold">Review whitelist transaction</h1><p className="mt-3">Exact saved Brickken preparation. No transaction is sent until you review and press submit.</p></div><dl className="divide-y rounded-xl border bg-white text-slate-900">{rows.map(([label,value])=><div key={label} className="grid gap-2 p-4 sm:grid-cols-[190px_1fr]"><dt className="font-semibold">{label}</dt><dd className="break-all font-mono text-sm">{value}</dd></div>)}</dl><label className="flex items-start gap-3"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>I reviewed the exact prepared whitelist transaction and want MetaMask to ask for confirmation.</span></label><button type="button" onClick={submit} disabled={!reviewed||pending} className="rounded-lg bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40">{pending?"Waiting for MetaMask…":"Submit whitelist transaction"}</button>{error&&<p role="alert" className="rounded-lg border border-red-300 bg-red-50 p-4 text-red-800">{error}</p>}{hash&&<div role="status" className="rounded-lg border border-green-300 p-4"><p className="font-semibold">MetaMask returned a transaction hash</p><p className="mt-2 break-all font-mono">{hash}</p><a className="mt-2 inline-block underline" href={"https://sepolia.basescan.org/tx/"+hash} target="_blank" rel="noreferrer">View on Base Sepolia explorer</a></div>}</main>;
}
